# Generated by Django 6.0 on 2026-01-21 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCourse',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('about_me', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('skills', models.TextField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates1/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('student_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer', models.CharField(max_length=100)),
                ('want', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Basic', max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUploadedCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='student_certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_certificates', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudyConnection',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Started', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_owner', to='students.student')),
                ('student1_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_as_student1', to='students.studentskill')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_partner', to='students.student')),
                ('student2_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_as_student2', to='students.studentskill')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_path', models.FileField(upload_to='resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studyconnection')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_value', models.IntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='students.student')),
                ('rated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='students.student')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studyconnection')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studyconnection')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('want_skill', models.CharField(max_length=100)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studyconnection')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_file', models.FileField(upload_to='assessments/')),
                ('validation_form_file', models.FileField(upload_to='validation_forms/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Ongoing', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studyconnection')),
            ],
        ),
    ]
