# Generated by Django 6.0 on 2026-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teacher_remove_studyconnection_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
    ]
