# Generated by Django 6.0 on 2026-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_teacher_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyconnection',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Progress', 'Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Started', max_length=30),
        ),
    ]
