# Generated by Django 6.0 on 2026-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studyconnection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_file',
            field=models.FileField(blank=True, null=True, upload_to='assessments/'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='validation_form_file',
            field=models.FileField(blank=True, null=True, upload_to='validation_forms/'),
        ),
    ]
