# Generated by Django 6.0 on 2026-01-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_assessment_assessment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyconnection',
            name='mentor_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studyconnection',
            name='mentor_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
