# Generated by Django 6.0 on 2026-01-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studyconnection_mentor_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyconnection',
            name='mentor_status',
        ),
        migrations.RemoveField(
            model_name='studyconnection',
            name='mentor_token',
        ),
    ]
