# Generated by Django 6.0 on 2026-01-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_studyconnection_mentor_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='want_skill',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
