# Generated by Django 6.0 on 2026-01-30 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_certificate_want_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
