# Generated by Django 6.0 on 2026-01-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_skillpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentskill',
            name='student_skill_id',
        ),
        migrations.AddField(
            model_name='studentskill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentskill',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentskill',
            name='offer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentskill',
            name='want',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
