# Generated by Django 6.0 on 2026-01-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_skillpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentskill',
            name='offer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentskill',
            name='want',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
