# Generated by Django 6.0 on 2026-01-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_studentskill_student_skill_id_and_more'),
        ('students', '0011_studentskill_description_alter_studentskill_offer_and_more'),
    ]

    operations = [
    ]
