# Generated by Django 6.0 on 2026-01-31 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_merge_20260131_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentskill',
            name='id',
        ),
        migrations.AddField(
            model_name='studentskill',
            name='student_skill_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentskill',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Basic', max_length=10),
        ),

    ]
