# Generated by Django 6.0 on 2026-01-31 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_helpsupport_websitereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipcourse',
            name='is_admin_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internshipcourse',
            name='posted_by_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
