# Generated by Django 6.0 on 2026-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_internshipcourse_is_admin_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
