# Generated by Django 6.0 on 2026-02-04 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_otp_expiry_student_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsupport',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.teacher'),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
