# Generated by Django 6.0 on 2026-02-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_helpsupport_teacher_alter_helpsupport_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
