# Generated by Django 6.0 on 2026-02-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_teacher_otp_expiry_teacher_reset_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reset_otp',
        ),
        migrations.AddField(
            model_name='teacher',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
