# Generated by Django 6.0 on 2026-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_teacher_otp_expiry_remove_teacher_reset_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='api_token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
