# Generated by Django 6.0 on 2026-02-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_teacher_api_token_remove_teacher_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
