# Generated by Django 6.0 on 2026-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_student_last_viewed_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
