# Generated by Django 6.0 on 2026-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
