# Generated by Django 6.0 on 2026-02-12 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_admin_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_viewed_help_center',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
